# Database
spring.datasource.url=jdbc:postgresql://${DB_HOST_CATEGORY:localhost}:${DB_PORT_CATEGORY:5432}/${DB_NAME_CATEGORY:areska}
spring.datasource.username=${DB_USERNAME_CATEGORY}
spring.datasource.password=${DB_PASSWORD_CATEGORY}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
server.port=${CATEGORY_SERVICE_PORT:8086}